### PR TITLE
Update the .css file for the dropdown content

### PR DESCRIPTION
**Pull request by HairforceNiko**

### CODE REVIEW

**Comment by eekaireb** [comment]
Why does the picture on the recipe page move to the left and push everything else down now? Is that intended?

**Comment by HairforceNiko** [comment]
I think originally the image is above the title.

**Comment by HairforceNiko** [comment]
> Why does the picture on the recipe page move to the left and push everything else down now? Is that intended?

**Comment by HairforceNiko** [comment]
> 

I think originally the image is above the title.

**Comment by eekaireb** [comment]
Can you merge like the fixed main branch into your branch and then we can test it and push it? I just don't want to break main again

**Review by eekaireb — APPROVED** [review]

**Pull request merged**
