### PR TITLE
Reorg

### PR DESCRIPTION
**Pull request by eekaireb**
### After creating your PR, please complete this checklist!

- [x] Go into cse110-fa21-group22/source/\_\_test\_\_/end-to-end.test.js
- [x] Change `const prNum = 0;` -> `const prNum = {your pr number};` _This should be on line 18_
- [x] Now push your change to the branch and it will rerun the checks

You are ready to finish the rest of the template.

---

### What were your changes

Reorganized the repo

---

### What specifically should be checked

That all of the features still work and that you can navigate between pages correctly

### CODE REVIEW

**Comment by demyinn00** [comment]
Preview does not work right now because we need to change the path to the webpages

**Comment by demyinn00** [comment]
Is the apikey out of fetches? The preview site works, but it can't fetch anything

**Comment by samanthaylin3** [comment]
yeah i think so

**Comment by eekaireb** [comment]
I wonder if we should change the text above the edit list mode to like specify that the lists are only edited locally

**Comment by eekaireb** [comment]
the deploy site works now for me though lol does it work for anyone else?

**Comment by demyinn00** [comment]
The site works for me now and i've tested favorites (remove fav, add fav, add list, delete from list, etc) and it seems good. Haven't found any issues

**Comment by samanthaylin3** [comment]
when i first went to the preview, it refreshes on the home page every time you add to favorites, but now it doesn't. so hopefully it doesnt happen again. on the home page and search page though the dropdown still pops up when you select cancel. im not sure how to fix :( and not sure if this is a big deal but when i get 0 results it says on 1/0 page.

**Comment by demyinn00** [comment]
The preview deployment link has been canceled so I can't check it out again to double check those errors :(

**Comment by samanthaylin3** [comment]
> 

that happened to me too, but when i refreshed the page it worked

**Comment by samanthaylin3** [comment]
> I wonder if we should change the text above the edit list mode to like specify that the lists are only edited locally. I feel like its confusing if they didnt ever try to unheart and thought it was a global delete.

yeah i think we should add like select recipes to be deleted from that list or copy to another list

**Comment by samanthaylin3** [comment]
would we need to change the api key in the future in case it charges elliot?

**Comment by eekaireb** [comment]
what do you mean? its a free one that you sent earlier rn

**Comment by samanthaylin3** [comment]
oh okay, idk how to check

**Review by samanthaylin3 — APPROVED** [review]

**Pull request merged**
