### PR TITLE
No reload recipe page

### LINKED ISSUE #325: no reload when favorite/unfavorite on recipe page

### PR DESCRIPTION
**Pull request by samanthaylin3**
### After creating your PR, please complete this checklist!

- [x] Go into cse110-fa21-group22/source/\_\_test\_\_/end-to-end.test.js
- [x] Change `const prNum = 0;` -> `const prNum = {your pr number};` _This should be on line 18_
- [x] Now push your change to the branch and it will rerun the checks

You are ready to finish the rest of the template.

---

### What were your changes

recipe.js so that it wouldn't reload every time we fav or unfav a recipe

---

### What specifically should be checked

1. adding to a list would update storage and change to red heart, then unfavoring it would prompt user if they are sure and if cancel nothing happens, and if yes then remove from all lists that its in all with no reload
2. adding a custom list would appear on the dropdown (unfavor and then try favoring it again) and that it functions like above without reloading
3. make sure dropdown works properly only showing up when it isn't favorited and user clicks on heart

### CODE REVIEW

**Review by eekaireb — CHANGES_REQUESTED** [review]
None of the recipes I favorited appear on the recipe page

**Comment by samanthaylin3** [comment]
what do you mean it doesn't appear on the recipe page?

**Comment by eekaireb** [comment]
> what do you mean it doesn't appear on the recipe page?

oops I meant the favorites page. like none of the lists or recipe cards load for me

**Comment by samanthaylin3** [comment]
oh thats a bug on the main, like every time you heart something from the recipe page and then go to favorites, it says nutrition isn't found. i saw in userlocalstorage that apparently theres two ways of fetching i think? im not really sure how the fetching works since i didnt work on that.

**Comment by eekaireb** [comment]
wait when did that bug start happening on main

**Comment by samanthaylin3** [comment]
im not sure :( it mightve been yesterday

**Review by HairforceNiko — APPROVED** [review]

**Pull request merged**
