### PR TITLE
No refresh on home when addtofavorite

### LINKED ISSUE #314: Do not reload page when "Add to favorite" button is clicked or item is unhearted on home page

### PR DESCRIPTION
**Pull request by DanlandYZ**
### After creating your PR, please complete this checklist!

- [x] Go into cse110-fa21-group22/source/\_\_test\_\_/end-to-end.test.js
- [x] Change `const prNum = 0;` -> `const prNum = {your pr number};` _This should be on line 18_
- [x] Now push your change to the branch and it will rerun the checks

You are ready to finish the rest of the template.

---

### What were your changes
1. Make the home page not refresh when the user favorite a recipe 

### In progress
1. Make the search page not refresh when the user favorite a recipe

---

### What specifically should be checked
1. check when user create a list by favorite on one recipeCard, it should reflect on all other cards meaning that all other cards should have that list as option.

### CODE REVIEW

**Comment by DanlandYZ** [comment]
need help with prettier :）

**Comment by samanthaylin3** [comment]
for the codefactor, if you click on it itll tell you where to fix.  like two files (recipe and search js) you have an extra space in from of the apikey for import apikey. and two files (searchpage and homepage js) wants you to add a "default" in front of export function (line 8 and 68)

**Review by samanthaylin3 — CHANGES_REQUESTED** [review]
on the homepage,  its not populating the favorites section as i add them like the video you sent in slack. and if i create a list, the next time i want to favorite something that new list isn't there. and after i add to a list, the dropdown doesn't go away.

on the search page, the dropdown doesn't go away after i favorite a recipe, unless i click cancel or another recipe. the new lists do show up here though!

one the favorites page, when i unheart something, it doesn't refresh and it is still there

**Comment by samanthaylin3** [comment]
I tried on my live server and it works. but its just the dropdown doesn't go away after you add it.

**Comment by samanthaylin3** [comment]
after the merge from main, its not working on live server anymore. it says it cant find the two imported functions

**Comment by eekaireb** [comment]
> after the merge from main, its not working on live server anymore. it says it cant find the two imported functions

oh I didnt realized I merged it. I was just resolving the conflicts in the e2e file

**Comment by HairforceNiko** [comment]
> after the merge from main, it's not working on the live server anymore. it says it can't find the two imported functions

I temporarily solve this problem. I make the page reload on the search page and never reload on the home page.

**Comment by DanlandYZ** [comment]
I think the dropdown goes away when mouse is not hovered on the recipeCard

**Comment by DanlandYZ** [comment]
Both homepage and searchPage should now hide dropdown after use favorite an recipe

**Pull request closed without merging**
